var c1={width:2,height:0.5,depth:15,}
var r1={width:4,height:0.5,depth:2,}
var c2={width:2,height:0.5,depth:5,}
var r2={width:5,height:0.5,depth:2,}
var c3={width:2,height:0.5,depth:4,}
var r3={width:7,height:0.5,depth:2,}
var c4={width:2,height:0.5,depth:2,}
var r4={width:2,height:0.5,depth:2,}
var r5={width:8,height:0.5,depth:2,}
var r7={width:18,height:0.5,depth:2,}
var c5={width:2,height:0.5,depth:3,}
var c6={width:2,height:0.5,depth:8,}
var c7={width:2,height:0.5,depth:12,}
var c8={width:2,height:0.5,depth:7,}
var c9={width:2,height:0.5,depth:20,}
var r8={width:5,height:0.5,depth:2}
var r9={width:3,height:0.5,depth:2,}
var r10={width:20,height:0.5,depth:2,}
var c10={width:2,height:0.5,depth:13,}
var flo={width:10,height:0.5,depth:10,}
var c11={width:2,height:0.5,depth:16,}
var fla={width:8,height:2,depth:0.01,}
var bs1={width:1.5,height:1.5,depth:1.5,}
var bs2={width:3,height:3,depth:3}
//製造地圖
/*變換規則
	col-row +(-(width/2)-1,0,+(col.depth/2)-1)
	row-col +(-(row.width/2)+1,0,depth/2+1)*/
function createMap(scene){
	var b1 = BABYLON.MeshBuilder.CreateBox('box', c1, scene);
	b1.position = new BABYLON.Vector3(0, -0.25, 7.5);//起始點(0,0,0)
	var b2 = BABYLON.MeshBuilder.CreateBox('box', r1, scene);
	b2.position = new BABYLON.Vector3(-3,-0.25,14);
	var b3 = BABYLON.MeshBuilder.CreateBox('box', c2, scene);
	b3.position = new BABYLON.Vector3(-4,-0.25,17.5); 
	var b4 = BABYLON.MeshBuilder.CreateBox('box', r1, scene);
	b4.position = new BABYLON.Vector3(-7,-0.25,19); 
	var b5 = BABYLON.MeshBuilder.CreateBox('box', c2, scene);
	b5.position = new BABYLON.Vector3(-8,-0.25,22.5); 
	var b6 = BABYLON.MeshBuilder.CreateBox('box', r3, scene);
	b6.position = new BABYLON.Vector3(-12.5,-0.25,24); 
	var b7 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b7.position = new BABYLON.Vector3(-15,-0.25,26); 
	var b8 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b8.position = new BABYLON.Vector3(-17,-0.25,26); 
	var b9 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b9.position = new BABYLON.Vector3(-17,-0.25,28);
	var b10 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b10.position = new BABYLON.Vector3(-19,-0.25,28); 
	var b11 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b11.position = new BABYLON.Vector3(-19,-0.25,30);
	var b12 = BABYLON.MeshBuilder.CreateBox('box', r5, scene);
	b12.position = new BABYLON.Vector3(-24,-0.25,30);
	var b13 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b13.position = new BABYLON.Vector3(-27,-0.25,32);
	var b14 = BABYLON.MeshBuilder.CreateBox('box', r3, scene);
	b14.position = new BABYLON.Vector3(-31.5,-0.25,32);
	var b15 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b15.position = new BABYLON.Vector3(-34,-0.25,34);
	var b16 = BABYLON.MeshBuilder.CreateBox('box', r7, scene);
	b16.position = new BABYLON.Vector3(-44,-0.25,34);
	var b17 = BABYLON.MeshBuilder.CreateBox('box', c2, scene);
	b17.position = new BABYLON.Vector3(-52,-0.25,37.5);
	var b18 = BABYLON.MeshBuilder.CreateBox('box', r2, scene);
	b18.position = new BABYLON.Vector3(-55,-0.25,39);
	var b19 = BABYLON.MeshBuilder.CreateBox('box', c3, scene);
	b19.position = new BABYLON.Vector3(-56.5,-0.25,42);
	var b20 = BABYLON.MeshBuilder.CreateBox('box', r2, scene);//
	b20.position = new BABYLON.Vector3(-59.5,-0.25,43);
	var b21 = BABYLON.MeshBuilder.CreateBox('box', c6, scene);
	b21.position = new BABYLON.Vector3(-61,-0.25,47.5);
	var b22 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b22.position = new BABYLON.Vector3(-63,-0.25,50.5);
	var b23 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b23.position = new BABYLON.Vector3(-63,-0.25,52.5);
	var b24 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);//
	b24.position = new BABYLON.Vector3(-65,-0.25,52.5);
	var b25 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b25.position = new BABYLON.Vector3(-65,-0.25,54.5);
	var b26 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b26.position = new BABYLON.Vector3(-67,-0.25,54.5);
	var b27 = BABYLON.MeshBuilder.CreateBox('box', c7, scene);
	b27.position = new BABYLON.Vector3(-67,-0.25,59.5);
	var b28 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b28.position = new BABYLON.Vector3(-69,-0.25,64.5);
	var b29 = BABYLON.MeshBuilder.CreateBox('box', c2, scene);
	b29.position = new BABYLON.Vector3(-69,-0.25,68);
	var b30 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b30.position = new BABYLON.Vector3(-71,-0.25,69.5);
	var b31 = BABYLON.MeshBuilder.CreateBox('box', c9, scene);
	b31.position = new BABYLON.Vector3(-71,-0.25,80.5);
	var b32 = BABYLON.MeshBuilder.CreateBox('box', r1, scene);
	b32.position = new BABYLON.Vector3(-74,-0.25,89.5);
	var b33 = BABYLON.MeshBuilder.CreateBox('box', c2, scene);
	b33.position = new BABYLON.Vector3(-75,-0.25,93);
	var b34 = BABYLON.MeshBuilder.CreateBox('box', r1, scene);
	b34.position = new BABYLON.Vector3(-78,-0.25,94.5);
	var b35 = BABYLON.MeshBuilder.CreateBox('box', c2, scene);
	b35.position = new BABYLON.Vector3(-79,-0.25,98);
	var b36 = BABYLON.MeshBuilder.CreateBox('box', r5, scene);
	b36.position = new BABYLON.Vector3(-84,-0.25,99.5);
	var b37 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b37.position = new BABYLON.Vector3(-87,-0.25,101.5);
	var b38 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b38.position = new BABYLON.Vector3(-89,-0.25,101.5);
	var b39 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b39.position = new BABYLON.Vector3(-89,-0.25,103.5);
	var b40 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b40.position = new BABYLON.Vector3(-91,-0.25,103.5);
	var b41 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b41.position = new BABYLON.Vector3(-91,-0.25,105.5);
	var b42 = BABYLON.MeshBuilder.CreateBox('box', r5, scene);
	b42.position = new BABYLON.Vector3(-96,-0.25,105.5);
	var b43 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b43.position = new BABYLON.Vector3(-99,-0.25,107.5);
	var b44 = BABYLON.MeshBuilder.CreateBox('box', r5, scene);
	b44.position = new BABYLON.Vector3(-104,-0.25,107.5);
	var b45 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b45.position = new BABYLON.Vector3(-107,-0.25,109);
	var b46 = BABYLON.MeshBuilder.CreateBox('box', r10, scene);
	b46.position = new BABYLON.Vector3(-118,-0.25,109);
	var b47 = BABYLON.MeshBuilder.CreateBox('box', c2, scene);
	b47.position = new BABYLON.Vector3(-127,-0.25,112.5);
	var b48 = BABYLON.MeshBuilder.CreateBox('box', r2, scene);
	b48.position = new BABYLON.Vector3(-130,-0.25,114);
	var b49 = BABYLON.MeshBuilder.CreateBox('box', c3, scene);
	b49.position = new BABYLON.Vector3(-131.5,-0.25,115.5);
	var b50 = BABYLON.MeshBuilder.CreateBox('box', r2, scene);
	b50.position = new BABYLON.Vector3(-134.5,-0.25,116.5);
	var b51 = BABYLON.MeshBuilder.CreateBox('box', c6, scene);
	b51.position = new BABYLON.Vector3(-136,-0.25,121);
	var b52 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b52.position = new BABYLON.Vector3(-138,-0.25,124.5);
	var b53 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b53.position = new BABYLON.Vector3(-138,-0.25,126.5);
	var b54 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b54.position = new BABYLON.Vector3(-140,-0.25,126.5);
	var b55 = BABYLON.MeshBuilder.CreateBox('box', c4, scene);
	b55.position = new BABYLON.Vector3(-140,-0.25,128.5);
	var b56 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b56.position = new BABYLON.Vector3(-142,-0.25,128.5);
	var b57 = BABYLON.MeshBuilder.CreateBox('box', c10, scene);
	b57.position = new BABYLON.Vector3(-142,-0.25,136);
	var b58 = BABYLON.MeshBuilder.CreateBox('box', r4, scene);
	b58.position = new BABYLON.Vector3(-144,-0.25,141.5);
	var b59 = BABYLON.MeshBuilder.CreateBox('box', c5, scene);
	b59.position = new BABYLON.Vector3(-144,-0.25,144);
	var b60 = BABYLON.MeshBuilder.CreateBox('box', r9, scene);
	b60.position = new BABYLON.Vector3(-146.5,-0.25,144.5);
	var b61 = BABYLON.MeshBuilder.CreateBox('box', c11, scene);
	b61.position = new BABYLON.Vector3(-147,-0.25,153.5);
	//endline
	var floor = BABYLON.MeshBuilder.CreateBox('box', flo, scene);
	floor.position = new BABYLON.Vector3(-147,-0.25,166.5);
	var cl1 = BABYLON.Mesh.CreateCylinder("cylinder",6,0.4,0.4,16,1,scene);
	cl1.position = new BABYLON.Vector3(-151,3,162.5);
	var cl2 = BABYLON.Mesh.CreateCylinder("cylinder",6,0.4,0.4,16,1,scene);
	cl2.position = new BABYLON.Vector3(-143,3,162.5);
	var flag = BABYLON.MeshBuilder.CreateBox('box', fla, scene);
	flag.position = new BABYLON.Vector3(-147,5,162.5);
	var materialFlag = new BABYLON.StandardMaterial("textureFlag", scene);
	materialFlag.diffuseTexture = new BABYLON.Texture("pic/end.png", scene);
	flag.material = materialFlag;
	var s1 = BABYLON.Mesh.CreateSphere("sphere", 15.0, 2, scene);
	s1.position = new BABYLON.Vector3(4.5, 2, 0);
	var s2 = BABYLON.Mesh.CreateSphere("sphere", 15.0, 2.5, scene);
	s2.position = new BABYLON.Vector3(-20, -3, 22);
	var s3 = BABYLON.Mesh.CreateSphere("sphere", 15.0, 3, scene);
	s3.position = new BABYLON.Vector3(-42, 2.5, 40);
	var s4 = BABYLON.Mesh.CreateSphere("sphere", 15.0, 3.5, scene);
	s4.position = new BABYLON.Vector3(-65, 1, 37);
	var s5 = BABYLON.Mesh.CreateSphere("sphere", 15.0, 4, scene);
	s5.position = new BABYLON.Vector3(-60, 2, 69);
	var s6 = BABYLON.Mesh.CreateSphere("sphere", 15.0, 4.5, scene);
	s6.position = new BABYLON.Vector3(-90, -3, 89);
	var torus = BABYLON.Mesh.CreateTorus("torus", 8, 0, 40, scene);
	torus.position = new BABYLON.Vector3(-90, -3, 89);
	var s7 = BABYLON.Mesh.CreateSphere("sphere", 15.0, 5, scene);
	s7.position = new BABYLON.Vector3(-110, 1, 120);
	var s8 = BABYLON.Mesh.CreateSphere("sphere", 15.0, 5.5, scene);
	s8.position = new BABYLON.Vector3(-150,- 2, 133);

	var b62 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b62.position = new BABYLON.Vector3(-155, 2,140);
	var b63 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b63.position = new BABYLON.Vector3(-140, 3,136);
	var b64 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b64.position = new BABYLON.Vector3(-133, 1.5,107);
	var b65 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b65.position = new BABYLON.Vector3(-120, -2,115);
	var b66 = BABYLON.MeshBuilder.CreateBox('box', bs2, scene);
	b66.position = new BABYLON.Vector3(-100, 2.5,99);
	var b67 = BABYLON.MeshBuilder.CreateBox('box', bs2, scene);
	b67.position = new BABYLON.Vector3(-155, 2,140);
	var b68 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b68.position = new BABYLON.Vector3(-90, 2,110);
	var b69 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b69.position = new BABYLON.Vector3(-80, -2,80);
	var b70 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b70.position = new BABYLON.Vector3(-68, 2,93);
	var b71 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b71.position = new BABYLON.Vector3(-63, 0,73);
	var b72 = BABYLON.MeshBuilder.CreateBox('box', bs2, scene);
	b72.position = new BABYLON.Vector3(-55, -1.5,62);
	var b73 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b73.position = new BABYLON.Vector3(-74, 2,55);
	var b74 = BABYLON.MeshBuilder.CreateBox('box', bs2, scene);
	b74.position = new BABYLON.Vector3(-55, 2,48);
	var b75 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b75.position = new BABYLON.Vector3(-53, 3.5,40);
	var b76 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b76.position = new BABYLON.Vector3(-50, 2,30);
	var b77 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b77.position = new BABYLON.Vector3(-43, 1,36);
	var b78 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b78.position = new BABYLON.Vector3(-35, 3.2,28);
	var b79 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b79.position = new BABYLON.Vector3(-30, 2,35);
	var b80 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b80.position = new BABYLON.Vector3(-25, -1.5,25);
	var b81 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b81.position = new BABYLON.Vector3(-20, 2.5,32);
	var b82 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b82.position = new BABYLON.Vector3(-15, 1,20);
	var b83 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b83.position = new BABYLON.Vector3(-4, -1.5,11);
	var b84 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b84.position = new BABYLON.Vector3(-8, 2.5,28);
	var b85 = BABYLON.MeshBuilder.CreateBox('box', bs1, scene);
	b85.position = new BABYLON.Vector3(-120, 2.5,100);
	var b86 = BABYLON.MeshBuilder.CreateBox('box', bs2, scene);
	b86.position = new BABYLON.Vector3(-132, 2.5,125);
	/*var lines = BABYLON.Mesh.CreateLines("lines", [
        new BABYLON.Vector3(4.5, 2, 0),
        new BABYLON.Vector3(-3, 5, 0),
        new BABYLON.Vector3(3, 0, -5),
        new BABYLON.Vector3(0, 1, 5)
	], scene);*/

	
	var materialPath = new BABYLON.StandardMaterial("texture1", scene);
	materialPath.diffuseTexture = new BABYLON.Texture("textures/grass.jpg", scene);
	b1.material = materialPath;
	b2.material = materialPath;	
	b3.material = materialPath;		
	b4.material = materialPath;
	b5.material = materialPath;	
	b6.material = materialPath;		
	b7.material = materialPath;
	b8.material = materialPath;	
	b9.material = materialPath;	
	b10.material = materialPath;

	b11.material = materialPath;	
	b12.material = materialPath;
	b13.material = materialPath;	
	b14.material = materialPath;
	b15.material = materialPath;	
	b16.material = materialPath;
	b17.material = materialPath;	
	b18.material = materialPath;
	b19.material = materialPath;	
	b20.material = materialPath;

	b21.material = materialPath;
	b22.material = materialPath;	
	b23.material = materialPath;		
	b24.material = materialPath;
	b25.material = materialPath;	
	b26.material = materialPath;		
	b27.material = materialPath;
	b28.material = materialPath;	
	b29.material = materialPath;		
	b30.material = materialPath;	

	b31.material = materialPath;
	b32.material = materialPath;	
	b33.material = materialPath;		
	b34.material = materialPath;
	b35.material = materialPath;	
	b36.material = materialPath;		
	b37.material = materialPath;
	b38.material = materialPath;	
	b39.material = materialPath;		
	b40.material = materialPath;

	b41.material = materialPath;
	b42.material = materialPath;	
	b43.material = materialPath;		
	b44.material = materialPath;
	b45.material = materialPath;	
	b46.material = materialPath;		
	b47.material = materialPath;
	b48.material = materialPath;	
	b49.material = materialPath;		
	b50.material = materialPath;

	b51.material = materialPath;
	b52.material = materialPath;	
	b53.material = materialPath;		
	b54.material = materialPath;
	b55.material = materialPath;	
	b56.material = materialPath;		
	b57.material = materialPath;
	b58.material = materialPath;	
	b59.material = materialPath;		
	b60.material = materialPath;
	b61.material = materialPath;
	floor.material = materialPath;
	var materialSphere1 = new BABYLON.StandardMaterial("texture2", scene);
	materialSphere1.diffuseTexture = new BABYLON.Texture("textures/Mercury.jpg", scene);
	s1.material = materialSphere1;

	var materialSphere2 = new BABYLON.StandardMaterial("texture3", scene);
	materialSphere2.diffuseTexture = new BABYLON.Texture("textures/Venus.jpg", scene);
	s2.material = materialSphere2;

	var materialSphere3 = new BABYLON.StandardMaterial("texture4", scene);
	materialSphere3.diffuseTexture = new BABYLON.Texture("textures/earth.jpg", scene);
	s3.material = materialSphere3;

	var materialSphere4 = new BABYLON.StandardMaterial("texture5", scene);
	materialSphere4.diffuseTexture = new BABYLON.Texture("textures/Mars.jpg", scene);
	s4.material = materialSphere4;

	var materialSphere5 = new BABYLON.StandardMaterial("texture6", scene);
	materialSphere5.diffuseTexture = new BABYLON.Texture("textures/Jupiter.jpg", scene);
	s5.material = materialSphere5;

	var materialSphere6 = new BABYLON.StandardMaterial("texture7", scene);
	materialSphere6.diffuseTexture = new BABYLON.Texture("textures/Saturn.jpg", scene);
	s6.material = materialSphere6;
	torus.material = materialSphere6;

	var materialSphere7 = new BABYLON.StandardMaterial("texture8", scene);
	materialSphere7.diffuseTexture = new BABYLON.Texture("textures/Uranus.png", scene);
	s7.material = materialSphere7;

	var materialSphere8 = new BABYLON.StandardMaterial("texture9", scene);
	materialSphere8.diffuseTexture = new BABYLON.Texture("textures/Neptune.jpg", scene);
	s8.material = materialSphere8;

	var materialBox1 = new BABYLON.StandardMaterial("texture10", scene);
	materialBox1.diffuseTexture = new BABYLON.Texture("textures/t1.jpg", scene);
	b62.material = materialBox1;
	b67.material = materialBox1;
	b72.material = materialBox1;
	b77.material = materialBox1;
	b82.material = materialBox1;
	var materialBox2 = new BABYLON.StandardMaterial("texture11", scene);
	materialBox2.diffuseTexture = new BABYLON.Texture("textures/t2.jpg", scene);
	b63.material = materialBox2;
	b68.material = materialBox2;
	b73.material = materialBox2;
	b78.material = materialBox2;
	var materialBox3 = new BABYLON.StandardMaterial("texture12", scene);
	materialBox3.diffuseTexture = new BABYLON.Texture("textures/t3.jpg", scene);
	b64.material = materialBox3;
	b69.material = materialBox3;
	b74.material = materialBox3;
	var materialBox4 = new BABYLON.StandardMaterial("texture13", scene);
	materialBox4.diffuseTexture = new BABYLON.Texture("textures/t4.jpg", scene);
	b65.material = materialBox4;
	b70.material = materialBox4;
	b75.material = materialBox4;
	b80.material = materialBox4;
	b83.material = materialBox4;
	var materialBox5 = new BABYLON.StandardMaterial("texture14", scene);
	materialBox5.diffuseTexture = new BABYLON.Texture("textures/t5.jpg", scene);
	b71.material = materialBox5;
	b76.material = materialBox5;
	b81.material = materialBox5;
	b84.material = materialBox5;

	var materialBox6 = new BABYLON.StandardMaterial("texture15", scene);
	materialBox6.diffuseTexture = new BABYLON.Texture("textures/t6.jpg", scene);
	b86.material = materialBox6;
	b79.material = materialBox6;
	b66.material = materialBox5;
	b85.material = materialBox5;
	
	return scene;
}